### ISSUE TITLE
Rule of 5 (Copy + Move Construction)

### ISSUE THREAD

**Issue by Aleksbgbg** [Isetta-Team/Isetta-Engine#4]
I've been browsing the code for a bit, and noticed that classes which define destructors don't follow the rule of 5 - they don't define copy and move constructors and operators.

Below is an example from the constructor definitions in `StackAllocator.h`:
https://github.com/Isetta-Team/Isetta-Engine/blob/bd461216740d6191dd53652deae0645f48488828/Isetta/IsettaEngine/Core/Memory/StackAllocator.h#L14-L16

I wanted to ask whether this was a design decision? I understand that adding all of the constructors would be painful work for no effective reason.

The reason the rule of 5 is an issue is that, when dealing with allocated memory (which is what destructors are usually used for - to free allocated memory), copying a class could cause one of the copies to have their memory freed by the other, causing invalid operations on one of the copies.

I've created an example `StackAllocator` which defines all copy and move constructor members, and is copy-safe (two copies will allocate to the same memory block, so it can be used in multiple places), present in this folder:
https://github.com/Aleksbgbg/Steamroller/tree/master/Steamroller/Memory
(heavily inspired by yours and the guidance in Game Engine Architecture, by the way)

Do you guys think it is worthwhile implementing "rule of 5" throughout the engine?
Was the omission of such an implementation a design choice?
Do you see a reason why copies of `StackAllocator` would be needed?

**Comment by cbiasco** [comment]
@zhuyidiwow should answer this, he did most of our memory work.
From my understanding, we never used more than one `StackAllocator` within our system and it was always abstracted away by higher level memory managers. So we never had any bugs arise from the problems that you're describing :)

In general, the rule of 5 is a good idea. If you have the time to do it, then you should do it. We didn't do it in our engine because we were more concerned with iteration, improvement, and progress than we were with stability and good engineering patterns. In an environment where we're building a game engine to make actual products with or that we expect to use for many years to come, these are definitely things we would have considered, but the 3 month time limit made us forego a lot of good standards and practices haha.

**Comment by Aleksbgbg** [comment]
I completely agree with the reasoning.

One thing I would say though is to make this decision explicit and forbid the compiler from copying or moving types:
```cpp
class MyType
{
public:
    MyType() = delete;
    MyType(const MyType&) = delete;
    MyType(MyType&&) = delete;

    ~MyType() = default;

public:
    MyType& operator=(const MyType&) = delete;
    MyType& operator=(MyType&&) = delete;
};
```

The above type still follows the rule of 5, simply by removing access to those operators.

**Comment by zhuyidiwow** [comment]
Hey Aleksbgbg,

I like your suggestions! That does make the code safer without causing too
much work.

Back to your earlier questions, we don't think a strict "copy" of memory
allocators would be needed cause otherwise they would "fight" for the same
memory resources and cause weird bugs. So if you do define a copy
constructor for StackAllocator, make sure you don't point their head memory
pointer to the same address, maybe only copying properties like size and
alignment and construct a new one is a better approach.

In our engine, we only have one stack allocator so we never encountered
such problems. However, if you are making a multi-threaded engine, it's a
common practice to let each thread have their own stack allocator and other
memory allocators so different threads don't need to get resources from the
same place.

Hope you enjoy your own journey of building a game engine! Don't forget our
blogs <https://isetta.io/> contain the most useful and detailed resources,
and let us know if you have any questions or found other smelly things in
our codebase. We greatly appreciated your effort!

Best,
Yidi

**Comment by Aleksbgbg** [comment]
I actually *did* write the StackAllocator as copying to the same memory - I haven't made the class thread-safe, so yes, there would be one per thread. However, if the methods are called synchronously, then calling the method on a copy is like calling it on the original object.

My idea with copies was to ensure that the allocator can be passed down to other methods and classes within the game loop. However, I think references or pointers would do just as fine - I don't think the hassle of implementing copies was worth it.

Thanks for the clarifications. I will definitely be reading the blogs as I go along!
